### ISSUE TITLE
Option to keep URL — or provide an alternate key

### ISSUE THREAD

**Issue by saropa** [Abdelazeem777/cached_network_svg_image#11]
Hi, thanks for the package!

We are running into the problem when using images that are parameter driven — they all end up looking the same!

This duplication seems to be due to the cleaning / stripping that occurs here:

``` dart
static String _generateKeyFromUrl(String url) => url.split('?').first;
```

Example URLs we use are: 

   ```someurl.com?image=65```

or:

   ```someotherurl.com/image?id=65```

Again, sometimes a forced refresh is needed (such as when a server is updated) and commonly a timestamp or other token is put on the URL:

   ```anotherurl.com/image.svg?timestamp=123456```

Can I suggest allowing an optional override parameter such as ```String? cacheKey,``` to bypass the logic ?

Or option to keep the full URL — maybe hashing to clean it up, if that what ```_generateKeyFromUrl()``` is used for?

Cheers!

**Comment by Abdelazeem777** [comment]
Hi @saropa 
Could you please provide a URL example that makes this issue with you, to reproduce?

**Comment by saropa** [comment]
> Hi @saropa 
> 
> Could you please provide a URL example that makes this issue with you, to reproduce?
> 
> 

Sure thing

https://avatar.iran.liara.run/public/boy?username=Scott

https://avatar.iran.liara.run/public/girl?username=Scott-something-else

https://avatar.iran.liara.run/public/girl?username=Maria


Or basically any url with a necessary query

**Comment by Abdelazeem777** [comment]
Aha, got your point
Okay, I think we can pass an optional `cacheKey`

**Comment by Abdelazeem777** [comment]
Hello @saropa 

the provided URLs are not working with the `flutter_svg` package itself, so I guess the issue is not related to the `custom_network_svg_image` package. 🤷‍♂️

But anyway, your suggested solution of using the optional `cacheKey` is now added and you can use it on `v1.1.0` 🎉
Clossing this issue regarding the new update, but feel free to reopen it again if you are still facing any other issues.😊🙏
